# NOTE: The source HTML (astlibra-codex equip-grid) had no category header
# tags -- only item cards -- so the section comments below are inferred from
# the order/theming of the cards, not read from real headers. Rename/re-split
# them freely if you have the game's actual categories.
#
# `key_item=True` is set for every card that had the 'legendary' class; it
# defaults to False so common/rare items need no extra argument.
from BaseClasses import Item

from typing import Dict, NamedTuple


class ItemData(NamedTuple):
    code: int
    key_item: bool = False  # True for cards with the 'legendary' class


class AstLibraItem(Item):
    game: str = "AstLibra"  # match whatever `game` name your apworld uses elsewhere

#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#!TODO: REPLACE THIS OFFSETR WITH THE BASE AP ID!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


offset = 1_000_000

item_table: Dict[str, ItemData] = {
    # Recipes & Guides
    "Synthesis Recipes": ItemData(offset + 1),
    "Advanced Synthesis Recipes": ItemData(offset + 2),
    "Baker's Recipes": ItemData(offset + 3),
    "Alchemy Recipes": ItemData(offset + 4),

    # Travel & World Tree Items
    "The Book of Karon: Vol 36 (Travel)": ItemData(offset + 5),
    "Camping Set": ItemData(offset + 6),
    "Dew from the World Tree": ItemData(offset + 7),
    "Pekkochira Drops": ItemData(offset + 8),
    "World Tree Blossom": ItemData(offset + 9, key_item=True),

    # Light Sources
    "Torch": ItemData(offset + 10),
    "Lantern": ItemData(offset + 11),

    # Pickaxes
    "Wooden Pickaxe": ItemData(offset + 12),
    "Stone Pickaxe": ItemData(offset + 13),
    "Iron Pickaxe": ItemData(offset + 14),
    "Crystal Pickaxe": ItemData(offset + 15),
    "Demon God's Pickaxe": ItemData(offset + 16),

    # Chest Keys & Materials
    "Copper Chests Key": ItemData(offset + 17),
    "Silver Chests Key": ItemData(offset + 18),
    "Gold Chests Key": ItemData(offset + 19),
    "Gunpowder": ItemData(offset + 20),
    "Key Mold A": ItemData(offset + 21),
    "Key Mold B": ItemData(offset + 22),

    # Libra & Slot Unlocks
    "Reset Potion": ItemData(offset + 23),
    "Trinkets Slot +1": ItemData(offset + 24, key_item=True),
    "Mokyun Doll": ItemData(offset + 25, key_item=True),

    # Ranged Weapons & Throwables
    "Throwing Knives": ItemData(offset + 26),
    "Wooden Boomerang": ItemData(offset + 27),
    "Bomb": ItemData(offset + 28),
    "Gunpowder Bullet": ItemData(offset + 29),
    "Quiver": ItemData(offset + 30),
    "Wooden Arrows": ItemData(offset + 31),
    "Wooden Bow": ItemData(offset + 32),
    "Yggdrasil Bow": ItemData(offset + 33),
    "Torch Bow": ItemData(offset + 34),
    "Spirit Bow Ushas": ItemData(offset + 35, key_item=True),
    "Crossbow": ItemData(offset + 36),
    "Double Crossbow": ItemData(offset + 37),
    "Shotgun": ItemData(offset + 38),
    "Laser Gun": ItemData(offset + 39),
    "Vijaya": ItemData(offset + 40),

    # Divine Drinks
    "Soma": ItemData(offset + 41),
    "Nectar": ItemData(offset + 42),
    "Amrita": ItemData(offset + 43),
    "Ambrosia": ItemData(offset + 44),

    # Medicine
    "Numbness-relieving Medicine": ItemData(offset + 45),
    "Eye Medicine": ItemData(offset + 46),
    "Hemostatic": ItemData(offset + 47),
    "Holy Water": ItemData(offset + 48),
    "Antitoxin": ItemData(offset + 49),

    # Bottles
    "Small Empty Bottle": ItemData(offset + 50),
    "Empty Bottle": ItemData(offset + 51),
    "Large Empty Bottle": ItemData(offset + 52),
    "Small Water-filled Bottle": ItemData(offset + 53),
    "Water-filled Bottle": ItemData(offset + 54),
    "Large Water-filled Bottle": ItemData(offset + 55),

    # Wild Fruits
    "Goji Berries": ItemData(offset + 56),
    "Cactus Fruit": ItemData(offset + 57),
    "Sapodilla Fruit": ItemData(offset + 58),
    "Tufted Fruit": ItemData(offset + 59),
    "Dogu Fruit": ItemData(offset + 60),

    # Sweets & Prepared Food
    "Sponge Cake": ItemData(offset + 61),
    "Egg on Bread": ItemData(offset + 62),
    "Cream Puff": ItemData(offset + 63),
    "Dango": ItemData(offset + 64),
    "Chocolate Cream Puff": ItemData(offset + 65),
    "Hamburger": ItemData(offset + 66),
    "Red Bean Manju": ItemData(offset + 67),
    "Jam Roll": ItemData(offset + 68),
    "Plain Cookies": ItemData(offset + 69),
    "Pie Dough": ItemData(offset + 70),
    "Cheesecake": ItemData(offset + 71),
    "Pancakes": ItemData(offset + 72),
    "Soft-Serve Ice Cream": ItemData(offset + 73),
    "Mont Blanc": ItemData(offset + 74),
    "Apple Pie": ItemData(offset + 75),
    "Strawberry Au Lait": ItemData(offset + 76),
    "Strawberry Crepe": ItemData(offset + 77),
    "Shortcake": ItemData(offset + 78),
    "Soft-Serve Chocolate Ice Cream": ItemData(offset + 79),
    "Chocolate Chip Cookie": ItemData(offset + 80),
    "Chocolate Pie": ItemData(offset + 81),
    "Hot Chocolate": ItemData(offset + 82),
    "Chocolate Cookie": ItemData(offset + 83),
    "Meat Pie": ItemData(offset + 84),
    "Soft Serve Matcha Ice Cream": ItemData(offset + 85),
    "Matcha Au Lait": ItemData(offset + 86),
    "Mochi Rolled in Bean Jam": ItemData(offset + 87),
    "Strawberry Jam": ItemData(offset + 88),
    "Cotton Candy": ItemData(offset + 89),
    "Strawberry Ice Cream": ItemData(offset + 90),
    "Jam Cookie": ItemData(offset + 91),
    "Candied Apple": ItemData(offset + 92),
    "Delicious Cake": ItemData(offset + 93),
    "Decorative Cake": ItemData(offset + 94),
    "Chocolate Cake": ItemData(offset + 95),
    "Sachertorte": ItemData(offset + 96),
    "Valentine Cake": ItemData(offset + 97),
    "Valentine Present": ItemData(offset + 98),

    # Cooking Ingredients
    "Egg": ItemData(offset + 99),
    "Flour": ItemData(offset + 100),
    "Butter": ItemData(offset + 101),
    "Cheese": ItemData(offset + 102),
    "Bread": ItemData(offset + 103),
    "Milk": ItemData(offset + 104),
    "Chestnut": ItemData(offset + 105),
    "Apple": ItemData(offset + 106),
    "Strawberry": ItemData(offset + 107),
    "Mochi": ItemData(offset + 108),
    "Chocolate": ItemData(offset + 109),
    "Cocoa": ItemData(offset + 110),
    "Beef": ItemData(offset + 111),
    "Tea Leaves": ItemData(offset + 112),
    "Red Bean Jam": ItemData(offset + 113),
    "Sugar": ItemData(offset + 114),

    # Books & Manuals
    "Formula": ItemData(offset + 115),
    "Book of Battle Records": ItemData(offset + 116),
    "Treasure Encyclopaedia": ItemData(offset + 117),
    "The Book of Mythology": ItemData(offset + 118),
    "Fairy Tales of the World": ItemData(offset + 119),
    "Introduction to Wizardry": ItemData(offset + 120),
    "Guidebook": ItemData(offset + 121),
    "Self-Made Item Book": ItemData(offset + 122),

    # Technique Scrolls
    "Technique Scroll - Sky Sword": ItemData(offset + 123),
    "Technique Scroll - Armor Slash": ItemData(offset + 124),
    "Technique Scroll - Counter Bash": ItemData(offset + 125),
    "Technique Scroll - Backstep": ItemData(offset + 126),
    "Technique Scroll - Shield Charge": ItemData(offset + 127),
    "Technique Scroll - Air Blade": ItemData(offset + 128),
    "Technique Scroll - Air Surf": ItemData(offset + 129),
    "Technique Scroll - Tornado Slash": ItemData(offset + 130),
    "Technique Scroll - Zero Gravity": ItemData(offset + 131),
    "Technique Scroll - Jump Slash": ItemData(offset + 132),

    # Sealed Technique Scrolls
    "Technique Sealing Medal": ItemData(offset + 133),
    "[Sealed] Technique Scroll - Sky Sword": ItemData(offset + 134),
    "[Sealed] Technique Scroll - Armor Slash": ItemData(offset + 135),
    "[Sealed] Technique Scroll - Counter Bash": ItemData(offset + 136),
    "[Sealed] Technique Scroll - Backstep": ItemData(offset + 137),
    "[Sealed] Technique Scroll - Shield Charge": ItemData(offset + 138),
    "[Sealed] Technique Scroll - Air Blade": ItemData(offset + 139),
    "[Sealed] Technique Scroll - Air Surf": ItemData(offset + 140),
    "[Sealed] Technique Scroll - Tornado Slash": ItemData(offset + 141),
    "[Sealed] Technique Scroll - Zero Gravity": ItemData(offset + 142),
    "[Sealed] Technique Scroll - Jump Slash": ItemData(offset + 143),

    # Diaries & Letters
    "The Priest's Diary": ItemData(offset + 144),
    "Diary Fragment": ItemData(offset + 145),
    "Well Epistle": ItemData(offset + 146),

    # Stat Cards
    "Physical Fitness Card": ItemData(offset + 147),
    "Stamina Card": ItemData(offset + 148),
    "Attack Power Card": ItemData(offset + 149),
    "Defense Power Card": ItemData(offset + 150),
    "Magical Power Card": ItemData(offset + 151),
    "Good Fortune Card": ItemData(offset + 152),
    "Agility Card": ItemData(offset + 153),
    "Adaption Card": ItemData(offset + 154),

    # Ores, Ingots & Refining Materials
    "Refining Kit": ItemData(offset + 155),
    "Clay-like Silver Stones": ItemData(offset + 156),
    "Clay-like Gold Stones": ItemData(offset + 157),
    "Stones": ItemData(offset + 158),
    "Copper Ore": ItemData(offset + 159),
    "Iron Ore": ItemData(offset + 160),
    "Gold Ore": ItemData(offset + 161),
    "High-carbon Steel Ore": ItemData(offset + 162),
    "Magical Silver Ore": ItemData(offset + 163),
    "Adamantine": ItemData(offset + 164),
    "Hihi-Irokane": ItemData(offset + 165),
    "Copper Ingot": ItemData(offset + 166),
    "Iron Ingot": ItemData(offset + 167),
    "Gold Ingot": ItemData(offset + 168),
    "Damascus Ingot": ItemData(offset + 169),
    "Mithril": ItemData(offset + 170),
    "Adamantite": ItemData(offset + 171),
    "Orichalcum": ItemData(offset + 172),
    "Atega": ItemData(offset + 173),
    "Tozupa": ItemData(offset + 174),
    "Erameld": ItemData(offset + 175),
    "Sirpphae": ItemData(offset + 176),
    "Byru": ItemData(offset + 177),
    "Daimond": ItemData(offset + 178, key_item=True),

    # Piece Gems
    "Piece Gem Fragment": ItemData(offset + 179),
    "Large Piece Gem Fragment": ItemData(offset + 180),
    "Piece Gem [Health]": ItemData(offset + 181, key_item=True),
    "Piece Gem [Stamina]": ItemData(offset + 182, key_item=True),
    "Piece Gem [Attack power]": ItemData(offset + 183, key_item=True),
    "Piece Gem [Defense power]": ItemData(offset + 184, key_item=True),
    "Piece Gem [Magical power]": ItemData(offset + 185, key_item=True),
    "Piece Gem [Agility]": ItemData(offset + 186, key_item=True),
    "Piece Gem [Luck]": ItemData(offset + 187, key_item=True),
    "Piece Gem [Adaptability]": ItemData(offset + 188, key_item=True),
    "Piece Gem [Guard Durability]": ItemData(offset + 189, key_item=True),
    "Piece Gem [Weight Reduction]": ItemData(offset + 190, key_item=True),
    "Piece Gem [Walking Speed]": ItemData(offset + 191, key_item=True),
    "Piece Gem [Stat Point Cap]": ItemData(offset + 192, key_item=True),
    "Piece Gem [Change [Possession Skill]]": ItemData(offset + 193, key_item=True),
    "Piece Gem [Change Karon Magic]": ItemData(offset + 194, key_item=True),
    "Piece Gem [Weapon Attributes]": ItemData(offset + 195, key_item=True),

    # Monster Drop Materials
    "Slime's Eyeball": ItemData(offset + 196),
    "Wooden Log": ItemData(offset + 197),
    "Cobweb": ItemData(offset + 198),
    "Bat Wings": ItemData(offset + 199),
    "Beautiful Bones": ItemData(offset + 200),
    "Revolting Meat": ItemData(offset + 201),
    "Mandragora": ItemData(offset + 202),
    "Tadpole": ItemData(offset + 203),
    "Poinsettia": ItemData(offset + 204),
    "Filthy Fang": ItemData(offset + 205),
    "Charcoal": ItemData(offset + 206),
    "Lava Pebble": ItemData(offset + 207),
    "Putrid Gill": ItemData(offset + 208),
    "Demon Horn": ItemData(offset + 209),
    "Golem Fragment": ItemData(offset + 210),
    "Hawk Feather": ItemData(offset + 211),
    "Turtle Shell": ItemData(offset + 212),
    "Crab Stick": ItemData(offset + 213),
    "Sashimi": ItemData(offset + 214),
    "Monkfish Liver": ItemData(offset + 215),
    "Claystones": ItemData(offset + 216),
    "Minotaur's Axe": ItemData(offset + 217),
    "Mammon's Feet": ItemData(offset + 218),
    "Lizard Scales": ItemData(offset + 219),
    "Gargoyle's Wings": ItemData(offset + 220),
    "Heat Exhaust Organ": ItemData(offset + 221),
    "Slime Jelly": ItemData(offset + 222),
    "Penguin's Egg": ItemData(offset + 223),
    "Clean Ice": ItemData(offset + 224),
    "Yeti's Fur": ItemData(offset + 225),
    "Shield of Rispadar": ItemData(offset + 226),
    "Slice of Ancient Fish": ItemData(offset + 227),
    "Godly Wings": ItemData(offset + 228),
    "Mirror Fragment": ItemData(offset + 229),
    "Magical Jar": ItemData(offset + 230),
    "Grasshopper's Wings": ItemData(offset + 231),
    "Insect Feet": ItemData(offset + 232),
    "Bewitched Tree Branch": ItemData(offset + 233),
    "Beastly Tree's Fungi": ItemData(offset + 234),
    "Tough Leg Meat": ItemData(offset + 235),
    "Dual Attribute Core": ItemData(offset + 236),
    "Spider Butt": ItemData(offset + 237),
    "Bolts": ItemData(offset + 238),
    "Cable": ItemData(offset + 239),
    "Gear": ItemData(offset + 240),
    "Battery": ItemData(offset + 241),
    "Screws": ItemData(offset + 242),
    "Heart": ItemData(offset + 243),
    "Spring": ItemData(offset + 244),
    "Nuclear Power Reactor": ItemData(offset + 245),
    "Primordial Fragment": ItemData(offset + 246),

    # Treasures & Key Items
    "Anulis' Ribbon": ItemData(offset + 247),
    "Withered Legendary Herb": ItemData(offset + 248),
    "Legendary Herb": ItemData(offset + 249, key_item=True),
    "Red Orb": ItemData(offset + 250),
    "Blue Orb": ItemData(offset + 251),
    "18 Liter Container of Pine Resin": ItemData(offset + 252),
    "Bundle of Wooden Sticks": ItemData(offset + 253),
    "Wonder Drug Fruit": ItemData(offset + 254),
    "Wooden Skull": ItemData(offset + 255),
    "Silver Skull": ItemData(offset + 256),
    "Gold Skull": ItemData(offset + 257),
    "Goblin's Stone Plate": ItemData(offset + 258),
    "Stone Plate Fragment (Upper)": ItemData(offset + 259),
    "Stone Plate Fragment (Lower)": ItemData(offset + 260),
    "Pretty Seashell": ItemData(offset + 261),
    "Golden Rice Ears": ItemData(offset + 262),
    "Pure White Garment": ItemData(offset + 263),
    "Apples from the King's Castle": ItemData(offset + 264),
    "Red Gem": ItemData(offset + 265),
    "Blue Gem": ItemData(offset + 266),
    "Green Gem": ItemData(offset + 267),
    "Girl's Earrings": ItemData(offset + 268),
    "Sluice Key": ItemData(offset + 269),
    "Ancient Key": ItemData(offset + 270),
    "Iron Bars Key": ItemData(offset + 271),
    "Security Card": ItemData(offset + 272),
    "Red Rune": ItemData(offset + 273),
    "Blue Rune": ItemData(offset + 274),
    "Purple Rune": ItemData(offset + 275),
    "Green Rune": ItemData(offset + 276),
    "Herb": ItemData(offset + 277),
    "Sleeping Aid": ItemData(offset + 278),
    "Metal and Glass Plank": ItemData(offset + 279),
    "Translocation Stone": ItemData(offset + 280),
    "Anulis' Brain": ItemData(offset + 281),
    "Bread?": ItemData(offset + 282),
    "Magical Crystals": ItemData(offset + 283),
    "Small Metal": ItemData(offset + 284),
    "Scale Pans": ItemData(offset + 285, key_item=True),
    "Golden Ticket": ItemData(offset + 286),
    "Red Stone": ItemData(offset + 287),
    "Blue Stone": ItemData(offset + 288),
    "Green Stone": ItemData(offset + 289),
    "Yellow Stone": ItemData(offset + 290),
    "Purple Stone": ItemData(offset + 291),
    "Yellow-green Gem": ItemData(offset + 292),
    "Red-yellow Gem": ItemData(offset + 293),
    "White Gem": ItemData(offset + 294),
    "Dark Gem": ItemData(offset + 295),
    "Sun Stone": ItemData(offset + 296),
    "Alexandrite": ItemData(offset + 297, key_item=True),
    "Love": ItemData(offset + 298, key_item=True),
    "Decorative Box": ItemData(offset + 299),
    "Battery (Muramasa)": ItemData(offset + 300, key_item=True),
}
